#!/bin/sh

logger "ip up"

baseName=`dirname $0`
ipList=`cat $baseName/../IP|sed -e '/^#/ s/.*//g' 2>&1`
for ip in $ipList ; do
        echo ip: $ip

        echo "route add $ip $PPP_IFACE"
        route add $ip $PPP_IFACE
done
~      
